# Дашборд для Яндекс.Дзен

## Описание проекта

**Часть 1. Составление технического задания**

Вы работаете аналитиком в Яндекс.Дзене. Почти всё ваше время занимает анализ пользовательского взаимодействия с карточками статей.

Каждую карточку определяют её тема и источник (у него тоже есть тема). Примеры тем: «Красота и здоровье», «Россия», «Путешествия».

Пользователей системы характеризует возрастная категория. Скажем, «26-30» или «45+».

Есть три способа взаимодействия пользователей с системой:
* Карточка отображена для пользователя `show`;
* Пользователь кликнул на карточку `click`;
* Пользователь просмотрел статью карточки `view`.

Каждую неделю начинающие менеджеры Денис и Валерия задают вам одни и те же вопросы: 
* Сколько взаимодействий пользователей с карточками происходит в системе с разбивкой по темам карточек?
* Как много карточек генерируют источники с разными темами?
* Как соотносятся темы карточек и темы источников?

На шестую неделю работы вы решаете, что процесс пора автоматизировать. Для Дениса и Валерии нужно сделать дашборд.
Дашборд будет основываться на пайплайне, который будет брать данные из таблицы, в которых хранятся сырые данные, трансформировать данные и укладывать их в агрегирующую таблицу. Пайплайн будет разработан для вас дата-инженерами.

**Пообщавшись с менеджерами и администраторами баз данных, вы написали краткое ТЗ:**

* Бизнес-задача: анализ взаимодействия пользователей с карточками Яндекс.Дзен;
* Насколько часто предполагается пользоваться дашбордом: не реже, чем раз в неделю;
* Кто будет основным пользователем дашборда: менеджеры по анализу контента;

Состав данных для дашборда:
* История событий по темам карточек (два графика - абсолютные числа и процентное соотношение);
* Разбивка событий по темам источников;
* Таблица соответствия тем источников темам карточек;

По каким параметрам данные должны группироваться:
* Дата и время;
* Тема карточки;
* Тема источника;
* Возрастная группа;

Характер данных:
* История событий по темам карточек — абсолютные величины с разбивкой по минутам;
* Разбивка событий по темам источников — относительные величины (% событий);
* Соответствия тем источников темам карточек - абсолютные величины;

* Важность: все графики имеют равную важность;
* Источники данных для дашборда: дата-инженеры обещали подготовить для вас агрегирующую таблицу dash_visits. Вот её структура:

`record_id` — первичный ключ,

`item_topic` — тема карточки,

`source_topic` — тема источника,

`age_segment` — возрастной сегмент,

`dt` — дата и время,

`visits` — количество событий.

* Таблица хранится в специально подготовленной для вас базе данных zen;
* Частота обновления данных: один раз в сутки, в полночь по UTC;

* Какие графики должны отображаться и в каком порядке, какие элементы управления должны быть на дашборде [макет дашборда](https://imgur.com/5eoKsUn)

**Часть 2. Создание дашборда**

Опубликуйте дашборд на сайте Tableau Public.

Ответьте на вопросы менеджеров, используя дашборд:
* Cколько взаимодействий пользователей с карточками происходит в системе с разбивкой по темам карточек?
* Как много карточек генерируют источники с разными темами?
* Как соотносятся темы карточек и темы источников?

Подготовьте небольшую презентацию с отчётом — ответы на вопросы и графики.

# Работа с проектом

**Импортируем все необходимые библиотеки для проекта**

In [1]:
# импортируем библиотеки
import pandas as pd
from sqlalchemy import create_engine

**Коннектимся к базе данных:**

In [2]:
#коннектимся к базе
db_config = {'user': 'praktikum_student', # имя пользователя
            'pwd': 'Sdf4$2;d-d30pp', # пароль
            'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
            'port': 6432, # порт подключения
            'db': 'data-analyst-zen-project-db'} # название базы данных

#запрашиваем сырые данные
connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
                                                db_config['pwd'],
                                                db_config['host'],
                                                db_config['port'],
                                                db_config['db'])

engine = create_engine(connection_string)

**Делаем sql запрос, выгружаю данные**

In [3]:
# делаем sql запрос

query = '''
           SELECT *
           FROM dash_visits
        '''

dash_visits = pd.io.sql.read_sql(query, con=engine)

**Выводим на экран первые 10 строк таблиц, изучаю данные**

In [4]:
dash_visits.head(10)

   record_id item_topic source_topic age_segment                  dt  visits
0    1040597     Деньги         Авто       18-25 2019-09-24 18:32:00       3
1    1040598     Деньги         Авто       18-25 2019-09-24 18:35:00       1
2    1040599     Деньги         Авто       18-25 2019-09-24 18:54:00       4
3    1040600     Деньги         Авто       18-25 2019-09-24 18:55:00      17
4    1040601     Деньги         Авто       18-25 2019-09-24 18:56:00      27
5    1040602     Деньги         Авто       18-25 2019-09-24 18:57:00      22
6    1040603     Деньги         Авто       18-25 2019-09-24 18:58:00      24
7    1040604     Деньги         Авто       18-25 2019-09-24 18:59:00      20
8    1040605     Деньги         Авто       18-25 2019-09-24 19:00:00       5
9    1040606     Деньги         Авто       26-30 2019-09-24 18:29:00       1

**Выводим сводную информацию о таблице**

In [5]:
dash_visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30745 entries, 0 to 30744
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   record_id     30745 non-null  int64
 1   item_topic    30745 non-null  object
 2   source_topic  30745 non-null  object
 3   age_segment   30745 non-null  object
 4   dt            30745 non-null  datetime64[ns]
 5   visits        30745 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 1.4+ MB

**Выводим на экран темы всех карточек**

In [6]:
dash_visits['item_topic'].value_counts()

Отношения             1536
Интересные факты      1535
Наука                 1505
Подборки              1456
Полезные советы       1424
Общество              1422
Россия                1385
История               1363
Семья                 1287
Путешествия           1247
Деньги                1234
Женщины               1230
Дети                  1229
Туризм                1206
Здоровье              1203
Красота               1193
Культура              1160
Юмор                  1129
Искусство             1119
Рассказы              1109
Психология            1056
Скандалы              1023
Знаменитости           976
Женская психология     914
Шоу                    804
Name: item_topic, dtype: int64

**Выводим на экран темы всех источников**

In [7]:
dash_visits['source_topic'].value_counts()

Семейные отношения    1822
Россия                1687
Знаменитости          1650
Полезные советы       1578
Путешествия           1563
Кино                  1505
Дети                  1459
История               1437
Семья                 1405
Одежда                1379
Здоровье              1243
Искусство             1228
Авто                  1077
Психология            1055
Сад и дача            1036
Политика              1024
Спорт                 1007
Сделай сам             995
Ремонт                 985
Деньги                 973
Еда                    912
Интерьеры              809
Строительство          758
Музыка                 750
Технологии             741
Финансы                667
Name: source_topic, dtype: int64

**Выводим на экран возрастной сегмент**

In [8]:
dash_visits['age_segment'].value_counts()

18-25    7056
26-30    5875
31-35    5552
36-40    5105
41-45    3903
45+      3254
Name: age_segment, dtype: int64

**Проверяю, за какой период представлены данные**

In [9]:
print(dash_visits['dt'].min())
print(dash_visits['dt'].max())

2019-09-24 18:28:00
2019-09-24 19:00:00

**Выгружаем файл в формате csv для работы в Tableau**

In [10]:
dash_visits.to_csv('dash_visits.csv', index = False)

# Дашборд

<https://public.tableau.com/app/profile/denis.volovik/viz/-_16837954030680/_?publish=yes>

# Презентация

<https://docs.google.com/presentation/d/11OBoiD11irlcjxv1g6DIdVD-u6dxDPsxSszB1bCDdlc/edit?usp=sharing>

# Общий вывод

Наименее популярные темы карточек:
* Знаменитости (1463 посещения)
* Шоу (1485 посещений)
* Женская психология (1518 посещений)

Наиболее популярные темы карточек:
* Наука (4372 посещения)
* Отношения (4145 посещения)
* Интересные факты (3910 посещений)

Наименее популярные темы источников:
* Финансы (0,85%)
* Музыка (0,92%)
* Строительство (0,87%)

Наиболее популярные темы источников:
* Семейные отношения (10,74%)
* Россия (9,62%)
* Полезные советы (8,84%)

Наиболее популярные связки (источник - тема карточки):
* Путешествия - рассказы (4587 посещений)
* Россия - общество (3471 посещение)
* Кино - наука (3279 посещений)